### ISSUE TITLE
"multiqueue" worker [feature request]

### ISSUE THREAD

**Issue by semsty** [yiisoft/queue#143]
useful functionality in production

with command `queue/listen ...` worker starts to listen several queues

there are several options for message processing:
1. randomly (messages are processed with random order from the channels list)
2. round-robin (messages are processed in order by channels list by one or batch)
3. by priority in channel list order (e.g. messages from queue-1 have priority over messages from queue-2, etc.)
4. ... other custom variations

**Comment by samdark** [comment]
What do you want to achieve by using a single worker for multiple queues?

**Comment by semsty** [comment]
Flexibility in infrastructure environment and between environments, saving limits of environment (e.g. number of processes or containers), etc. (i.e. it's more "devops" achievements)

Having one worker per queue in the case of large services can be redundant in terms of resources (for example, a limit on the number of pods in k8s).

For example, in a "big" production with 1000+ queues may need several workers, but in a test or localdev environment it may be more convenient to have one worker for 1000+ queues. (there is an option for one serviced queue in such environments, but it's looks less convenient and controllable since, for example, queues can have different configs)

Or, also for example, temporary reconfigurations of a large number of workers in the same k8s in the case of worker-nodes maintenance.

Similar functionality was peeped from Celery, i'm encountered the benefits of the possibility of such configurations.
