### ISSUE TITLE
Add Features for run-time checking of possible flow

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue#191]
Two examples from the documentation:
- Important: **_Not every adapter_** (such as synchronous adapter) **_supports delayed execution_**
- You can also check the status of a pushed message (**_the queue adapter you are using must support this feature_**)

Possibly 
- _Features_ should be added as first class citizens
- [AdapterInterface](https://github.com/yiisoft/queue/blob/master/src/Adapter/AdapterInterface.php) will return features supported by used adapter

This functionality will allow to develop common code for different adapters.

**Comment by samdark** [comment]
How many features are there that vary between adapters?

**Comment by g41797** [comment]
_How many features are there that vary between adapters?_
2 in old interface, 1 in new one:
...**_status of a pushed message_** (the queue adapter you are using **must support this feature**):

```php
$queue->push($message);
$id = $message->getId();

// Get status of the job
$status = $queue->status($id);

// Check whether the job is waiting for execution.
$status->isWaiting();

// Check whether a worker got the job from the queue and executes it.
$status->isReserved();

// Check whether a worker has executed the job.
$status->isDone();
```
may be to add NotSupported to JobStatus? instead of notes in README and 
```php
throw new NotImplementedException
```

### [**OFF THE TOPIC** just because [status:_under discussion_]]

I did not understand correlation between **_status of a pushed message_** and JobStatus:
 - status of pushed message really depends on functionality of specific adapter 
 - possibility to get status of the job depends on implementation of queue: status of the job may be saved(published) using the same adapter transparently to caller

Now i got the point - in current implementation adapter itself runs job and "knows" how to update message status. I though processing is duty of queue 

Part of methods may be called only on specific side of the queue:
- listen, run - on consumer side (ConsumerQueueInterface ?)
- push, status - on producer side (ProducerQueueInterface ?)

Possibility to cancel job or get process or progress indicator - LoopInterface does not have suitable methods and called only between jobs (not transferred to the handler). But this functionality very important for long running jobs

Lack of finish job status (at least i did not find whether it returned to producer) success or fail and what was the reason of the failure 
_Fire and forget_ style? But why we are asking about JobStatus?

Looks I don't understand queue usage by Yii applications

**Comment by g41797** [comment]
opened #192 to continue discussion

**Comment by samdark** [comment]
> Seems I don't understand queue usage by Yii applications

1. Background processing.
2. A way to exchange messages between the project and external world.

**Comment by g41797** [comment]
to be continued - see #192
