### ISSUE TITLE
Foreign (non-PHP) Workers

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue#194]
[Message format](https://github.com/yiisoft/queue/blob/master/docs/guide/migrating-from-yii2-queue.md#jobs-messages-and-handlers) allows processing of jobs using _non-PHP_ workers.

Foreign Worker requirements:
- Worker is CLI application
- listens on _YiiQueue_, receives _Messages_ and processes _Jobs_
- supports the same protocol and set of _drivers_ (RabbitMQ, Redis, etc)
- extendable: possibility to add 
  - new type of _driver_
  - job _handlers_ 

> "All the message data is fully serializable (that means message data must be serializable too)"

Additional requirements for PHP side:
- [use JSON encode instead of PHP serialization](https://accreditly.io/articles/phps-serialize-vs-json-when-to-serialize-and-when-to-json-encode)

Consider usage of [Cloud Events](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md) as [_envelope_](https://github.com/yiisoft/queue/blob/master/src/Message/EnvelopeInterface.php) for submitting jobs to Foreign Workers.

**Comment by xepozz** [comment]
It uses [json serializer](https://github.com/yiisoft/queue/blob/master/src/Message/JsonMessageSerializer.php) by default.
Making non-php workers is not responsibility of the package. Any workflow are possible. 
Should we close it?

**Comment by g41797** [comment]
```
It uses json serializer by default.
```
I know, but I need to read sources in order to understand...
```
Making non-php workers is not responsibility of the package.
```
I know, I'd like to discuss this functionality somewhere - it will be "added value" for Yii. I already started to design go part and need some assistance
```
Any workflow are possible.
```
Am not sure. API's and implementation are so PHP oriented. Possible we will need some adjustment on PHP side
```
Should we close it?
```
If your are not interested in improving of framework functionality

**Comment by xepozz** [comment]
Provide more details about the problems **when you have it**. 
Use telegram chat for real-time discussions if you don't want to describe the whole picture in each issue. 

Thanks.
