### ISSUE TITLE
A list of nice to add adapters. Feel free to make a proposition

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue#202]
[Title](https://github.com/php-enqueue/enqueue-dev/issues/284) was stollen. 

I created [NATS adapter repo](https://github.com/g41797/queue-nats) as public template for development of yii queue adapters.

"Feel free to make a proposition"

1. [Apache Pulsar](https://github.com/g41797/queue-pulsar)

**Comment by samdark** [comment]
- SQS/SNS.
- Kafka.

**Comment by samdark** [comment]
https://github.com/php-enqueue

**Comment by samdark** [comment]
- Beanstalkd
- Redis

**Comment by samdark** [comment]
- yiisoft/db
- RoadRunner queue

**Comment by g41797** [comment]
I'd like to add following issue for discussion - _dynamic list of features supported by channel_ (specific adapter):

- delay
- status
- etc

**Comment by g41797** [comment]
> * SQS/SNS.
> 

Regarding **SNS** - see [AWS SNS vs SQS](https://ably.com/topic/aws-sns-vs-sqs)
Looks SNS itself is not suitable for background processing
Only SNS+SQS combination, but it's too mach

**Comment by samdark** [comment]
Yes, they're usually used together.

**Comment by g41797** [comment]
Developed adapters:

There are other queue adapters contributed and maintained by the community and available on GitHub, such as:
* [NATS](https://github.com/g41797/queue-nats) - [NATS](https://nats.io/) JetStream adapter
* [Pulsar](https://github.com/g41797/queue-pulsar) - [Apache Pulsar](https://pulsar.apache.org/) adapter
* [SQS](https://github.com/g41797/queue-sqs) - [Amazon SQS](https://aws.amazon.com/sqs/) adapter
* [Kafka](https://github.com/g41797/queue-kafka) - [Apache Kafka](https://kafka.apache.org/) adapter
* [Valkey](https://github.com/g41797/queue-valkey) - [Valkey NoSQL data store ](https://valkey.io/) adapter
* [Beanstalkd](https://github.com/g41797/queue-beanstalkd) - [Beanstalkd - simple, fast work queue](https://beanstalkd.github.io/) adapter

Looks this issue may be closed as completed
